server:
  port: 8080
spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
mall:
  jwt:
    location: classpath:mall.jks
    alias: mall
    password: 123456
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /items/**