server:
  port: 8080
spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    nacos:
      server-addr: 192.168.60.10:8848
    gateway:
      routes:
        - id: item
          uri: lb://item-service
          predicates:
            - Path=/items/**,/search/**
        - id: cart
          uri: lb://cart-service
          predicates:
              - Path=/carts/**
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/users/**,/addresses/**
        - id: trade
          uri: lb://trade-service
          predicates:
            - Path=/orders/**
        - id: pay
          uri: lb://pay-service
          predicates:
            - Path=/pay-orders/**
#      default-filters:
#        - Custom=1,2,3
mall:
  jwt:
    location: classpath:mall.jks
    alias: mall
    password: 123456
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /items/**
      - /hi