server:
  port: 8083
spring:
  cloud:
    openfeign:
      httpclient:
        hc5:
          enabled: true
mall:
  jwt:
    location: classpath:mall.jks
    alias: mall
    password: 123456
    tokenTTL: 30m
  db:
    database: mall-user
