server:
  port: 8085
spring:
  cloud:
    openfeign:
      httpclient:
        hc5:
          enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /mall
    username: mall
    password: 666
mall:
  db:
    database: mall-pay

