server:
  port: 8082
  tomcat:
    threads:
      max: 25
    accept-count: 25
    max-connections: 100
spring:
  application:
    name: cart-service
    openfeign:
      httpclient:
        hc5:
          enabled: true
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090
      http-method-specify: true
mall:
  db:
    database: mall-cart
feign:
  sentinel:
    enabled: true